name=Wire
version=1.0.0
author=ArduinoCore-GD32V
maintainer=ArduinoCore-GD32V
sentence=I2C master library for GD32VW55x
paragraph=Arduino-compatible Wire API using the GD32VW553 I2C0 peripheral in master mode.
category=Communication
url=https://github.com/michaelng1129/ArduinoCore-GD32V
architectures=gd32vw55x
