name=SPI
version=1.0.0
author=ArduinoCore-GD32V
maintainer=ArduinoCore-GD32V
sentence=SPI master library for GD32VW55x
paragraph=Arduino-compatible SPI API using the GD32VW553 hardware SPI peripheral.
category=Communication
url=https://github.com/michaelng1129/ArduinoCore-GD32V
architectures=gd32vw55x
